### ISSUE TITLE
Downtown W Prefabs

### ISSUE THREAD

**Issue by softyay** [Capstone-System-Miami/Unity#39]
# Description
- Make four prefabs for the Downtown neighborhood the way that we went over in class.
- Find your personal folder within the project
   - You can find your folder at __Project > _ Prefabs > _ Environment > _ Prototyping > Intersections > [your name]_
   - Create your prefabs in this folder.
      - Duplicate (copy and paste) the BASE INTERSECTION prefab from your folder
      - Rename it to the name of the prefab you're working on
      - Double click it to enter "Prefab Editing" mode.
   - _**Work on your prefabs in the Prefab Editor, instead of in a scene**_

## Remember
- Work on your prefabs inside the Unity repo. Copy/pasting from other projects can result in rendering/texturing errors and general compatibility issues
- Every time you sit down work, _**Fetch & Pull**_ first.
- Every time you are about to stop working, even if you aren't totally done, _**Commit & Push**_
- If you have any questions, ask!

### Deliverables
- [x] Intersection_Downtown_W_1
- [x] Intersection_Downtown_W_2
- [x] Intersection_Downtown_W_3
- [x] Intersection_Downtown_W_4

**Comment by AntonyPinto03** [comment]
Hi! Prefabs are looking fine! There are some things that we can improve though.
I'll go prefab by prefab.

Intersection_Downtown_NWE_1
-
- Name should be NWE_1, NWE_2, etc.
- Street lines are off. I will upload a pic soonish on discord showing how should they look.
- Buildings are their own separate layer, nice!! But there are too many blocks inside of them that are affecting performance, and these blocks won't be seen by the player, so they should be removed (see image).

![Image](https://github.com/user-attachments/assets/2ac9f3ef-cb29-4a2c-b8d9-c528902192d7)
![Image](https://github.com/user-attachments/assets/6b4414f5-ad7c-440e-829a-065d173613ac)

Apart from that, it's looking good!

Intersection_Downtown_NWE_2
-
- Same issues as above

Intersection_Downtown_NWE_3
-
- Same issues as above

Intersection_Downtown_NWE_4
-
- Decoration (like trees, fences, lights, etc) should be drawn on their own tilemaps, just like the buildings.
- Same issues as above.

**Comment by AntonyPinto03** [comment]
I'll keep it going here,

Intersection_Downtown_W_1
-
- Same as before, too many blocks inside the building, naming, and decor on 'base' instead of it's own layer.

Intersection_Downtown_W_2
-
- Same as above.

Intersection_Downtown_W_3
-
- Same as above.

Intersection_Downtown_W_4
-
- Same as above.
