### ISSUE TITLE
Downtown ENS Prefabs

### ISSUE THREAD

**Issue by softyay** [Capstone-System-Miami/Unity#51]
# Description
- Make four prefabs for the Downtown neighborhood the way that we went over in class.
- Find your personal folder within the project
   - You can find your folder at __Project > _ Prefabs > _ Environment > _ Prototyping > Intersections > [your name]_
   - Create your prefabs in this folder.
      - Duplicate (copy and paste) the BASE INTERSECTION prefab from your folder
      - Rename it to the name of the prefab you're working on
      - Double click it to enter "Prefab Editing" mode.
   - _**Work on your prefabs in the Prefab Editor, instead of in a scene**_

## Remember
- Work on your prefabs inside the Unity repo. Copy/pasting from other projects can result in rendering/texturing errors and general compatibility issues
- Every time you sit down work, _**Fetch & Pull**_ first.
- Every time you are about to stop working, even if you aren't totally done, _**Commit & Push**_
- If you have any questions, ask!

### Deliverables
- [x] Intersection_Downtown_ENS_1
- [x] Intersection_Downtown_ENS_2
- [x] Intersection_Downtown_ENS_3
- [x] Intersection_Downtown_ENS_4

**Comment by softyay** [comment]
Hey!  You got assigned two sets of prefabs, so let us know if you think that's too much or you want to request help from another teammate 😊

**Comment by AntonyPinto03** [comment]
**Things to fix:**
I will go prefab by prefab.

ENS_1
-
(not to fix) You made the inside of the buildings empty, nice!!!! This will save us some performance, but I still want to leave these images here for future referencing.
![Image](https://github.com/user-attachments/assets/646e4299-4c5a-4eb2-9cbf-43599b58db01)
![Image](https://github.com/user-attachments/assets/b93933cb-47c6-49c4-8ed0-08d8f36ca017)

-  Naming of the prefab should be NSE, this might lead to confusions later.
- Street lines are not correct, I will be posting the correct street lines on discord soon.
- Building 2 and 3 order in layer should be 1.
ENS_2
-
-You made the inside of the building 1 full of unnecessary blocks, not nice. This will lead to performance issues.
-The order in layer should be 1 for objects with height.
-Naming of the prefab should be NSE.
-Street lines

Missing NSE 3 and 4
